# Generated by Django 2.0.6 on 2018-06-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=10)),
                ('ques', models.CharField(max_length=100)),
                ('ans', models.CharField(max_length=100)),
            ],
        ),
    ]
