# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-25 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serve', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='ans',
            new_name='Answer',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='level',
            new_name='Level',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='ques',
            new_name='Question',
        ),
    ]
