# Generated by Django 2.0.6 on 2018-06-27 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serve', '0002_auto_20180625_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='Answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Topic',
            new_name='topic',
        ),
    ]
